services:
  backend:
    image: 971598352774.dkr.ecr.ap-south-1.amazonaws.com/expense-backend:${IMAGE_TAG}
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ExpenseApp@1
    command: sh -c "sleep 30 && node /opt/backend/index.js"
    container_name: backend
    depends_on:
      - mysql
    networks:
      - expense

  mysql:
    image: 971598352774.dkr.ecr.ap-south-1.amazonaws.com/expense-mysql:${IMAGE_TAG}
    restart: always
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - expense

  frontend:
    image: 971598352774.dkr.ecr.ap-south-1.amazonaws.com/expense-frontend:${IMAGE_TAG}
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - backend
    networks:
      - expense

  nginx:
    image: nginx:1.28-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - expense

networks:
  expense:

volumes:
  mysql: