name: Expense App CI/CD

on:
  push:
    branches:
      - main

jobs:

  docker-build-and-push:

    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: 971598352774
      IMAGE_TAG: ${{ github.sha }}

    defaults:
      run:
        working-directory: expense-docker


    steps:

      ################################
      # Checkout Repository
      ################################

      - name: Checkout Repository
        uses: actions/checkout@v4


      ################################
      # Build Verification
      ################################

      - name: Verify Backend
        working-directory: expense-docker/backend
        run: |
          npm ci
          node --check index.js


      - name: Verify Frontend Nginx Configuration
        run: |
          docker build -t frontend-test ./frontend

          docker network create nginx-test

          docker run -d \
            --name backend \
            --network nginx-test \
            nginx:alpine

          docker run --rm \
            --network nginx-test \
            frontend-test nginx -t

          docker rm -f backend

          docker network rm nginx-test


      - name: Verify MySQL Image
        run: |
          docker build -t mysql-test ./mysql



      ################################
      # Configure AWS Credentials
      ################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}



      ################################
      # Login to Amazon ECR
      ################################

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2



      ################################
      # Backend Image
      ################################

      - name: Build Backend Image
        run: |
          docker build \
            -t expense-backend:${IMAGE_TAG} \
            ./backend


      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: expense-backend:${{ github.sha }}
          format: table
          exit-code: '0'
          severity: CRITICAL


      - name: Tag Backend Image
        run: |
          docker tag \
            expense-backend:${IMAGE_TAG} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-backend:${IMAGE_TAG}


      - name: Push Backend Image
        run: |
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-backend:${IMAGE_TAG}



      ################################
      # Frontend Image
      ################################

      - name: Build Frontend Image
        run: |
          docker build \
            -t expense-frontend:${IMAGE_TAG} \
            ./frontend


      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: expense-frontend:${{ github.sha }}
          format: table
          exit-code: '0'
          severity: CRITICAL


      - name: Tag Frontend Image
        run: |
          docker tag \
            expense-frontend:${IMAGE_TAG} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-frontend:${IMAGE_TAG}


      - name: Push Frontend Image
        run: |
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-frontend:${IMAGE_TAG}



      ################################
      # MySQL Image
      ################################

      - name: Build MySQL Image
        run: |
          docker build \
            -t expense-mysql:${IMAGE_TAG} \
            ./mysql


      - name: Scan MySQL Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: expense-mysql:${{ github.sha }}
          format: table
          exit-code: '0'
          severity: CRITICAL


      - name: Tag MySQL Image
        run: |
          docker tag \
            expense-mysql:${IMAGE_TAG} \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-mysql:${IMAGE_TAG}


      - name: Push MySQL Image
        run: |
          docker push \
            ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/expense-mysql:${IMAGE_TAG}
      ################################
      # Deploy to EC2
      ################################

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        env:
          IMAGE_TAG: ${{ github.sha }}
          AWS_REGION: ap-south-1
          AWS_ACCOUNT_ID: 971598352774

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          envs: IMAGE_TAG,AWS_REGION,AWS_ACCOUNT_ID

          script: |
            set -e

            cd /home/ubuntu/hello-world/expense-docker

            git pull origin main

            echo "IMAGE_TAG=${IMAGE_TAG}" > .env

            echo "Deploying image tag: ${IMAGE_TAG}"

            cat .env

            docker-compose config | grep image

            aws ecr get-login-password --region ${AWS_REGION} | \
            docker login \
              --username AWS \
              --password-stdin \
              ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

            docker-compose pull

            docker-compose up -d

            docker-compose ps

            docker image prune -f